### PR TITLE
[#916] - eslint-plugin-testing-library configurado

### PR DESCRIPTION
**Pull request by ErikGIovani**

### CODE REVIEW

**Comment by rolivencia** [comment]
Tenemos algunos errores de linting por las nuevas reglas, los cuales parecen (parecen) ser triviales. ¿Podrás revisarlos @ErikGIovani?

**Comment by ErikGIovani** [comment]
> Tenemos algunos errores de linting por las nuevas reglas, los cuales parecen (parecen) ser triviales. ¿Podrás revisarlos @ErikGIovani?
> 
> Aunque sean errores no deja de ser buena noticia: significa que podemos mejorar estas definiciones.
> 
> ```
> /home/runner/work/cuentoneta/cuentoneta/src/app/app.component.spec.ts
>   14:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
>   44:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/footer/footer.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/header/header.component.spec.ts
>   13:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/publication-card/publication-card.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/share-content/share-content.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-card-skeleton/story-card-skeleton.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-edition-date-label/story-edition-date-label.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-navigation-bar/story-navigation-bar.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/components/storylist-card-deck/storylist-card-deck.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/pages/about/about.component.spec.ts
>   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/pages/home/home.component.spec.ts
>   [18](https://github.com/cuentoneta/cuentoneta/actions/runs/10311728517/job/28545809834?pr=941#step:6:19):27  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/pages/story/story.component.spec.ts
>   21:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> 
> /home/runner/work/cuentoneta/cuentoneta/src/app/pages/storylist/storylist.component.spec.ts
>   27:27  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle```
> ```

Claro 👍, desactivo esas reglas?, La única que veo necesaria desactivar es la de  render-result-naming-convention, ya component si se me hace declarativo, comparado con view o utils.

Aquí hay mas info sobre el porque de cada rule:
- [no-render-in-lifecycle](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-render-in-lifecycle.md)
- [render-result-naming-convention](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/render-result-naming-convention.md)

**Comment by rolivencia** [comment]
> > Tenemos algunos errores de linting por las nuevas reglas, los cuales parecen (parecen) ser triviales. ¿Podrás revisarlos @ErikGIovani?
> > Aunque sean errores no deja de ser buena noticia: significa que podemos mejorar estas definiciones.
> > ```
> > /home/runner/work/cuentoneta/cuentoneta/src/app/app.component.spec.ts
> >   14:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
> >   44:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/footer/footer.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/header/header.component.spec.ts
> >   13:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/publication-card/publication-card.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/share-content/share-content.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-card-skeleton/story-card-skeleton.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-edition-date-label/story-edition-date-label.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/story-navigation-bar/story-navigation-bar.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/components/storylist-card-deck/storylist-card-deck.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/pages/about/about.component.spec.ts
> >   7:9  error  `component` is not a recommended name for `render` returned value. Instead, you should destructure it, or name it using one of: `view`, or `utils`  testing-library/render-result-naming-convention
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/pages/home/home.component.spec.ts
> >   [18](https://github.com/cuentoneta/cuentoneta/actions/runs/10311728517/job/28545809834?pr=941#step:6:19):27  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/pages/story/story.component.spec.ts
> >   21:21  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle
> > 
> > /home/runner/work/cuentoneta/cuentoneta/src/app/pages/storylist/storylist.component.spec.ts
> >   27:27  error  Forbidden usage of `render` within testing framework `beforeEach` setup  testing-library/no-render-in-lifecycle```
> > ```
> 
> Claro 👍, desactivo esas reglas?, La única que veo necesaria desactivar es la de render-result-naming-convention, ya que component si se me hace declarativo, comparado con view o utils.
> 
> Aquí hay mas info sobre el porque de cada rule:
> 
> * [no-render-in-lifecycle](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-render-in-lifecycle.md)
> * [render-result-naming-convention](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/render-result-naming-convention.md)

Preferiría que las mantengamos. Voy a hacer merge de estos cambios una vez que termine con #915, solucionando estos problemas de linting.

Dejamos abierto el PR hasta entonces. Luego procedo a hacer merge.

**Review by rolivencia — APPROVED** [review]
Resueltos todos los problemas de linting que surgieron con las nuevas reglas. GTG 🤝

**Pull request merged**
